### PR TITLE
Removed require 'dry/transaction/dsl' from dry/transaction/sequence

### LINKED ISSUE #38: Fix circular require warning
This showed up when running rake spec in a new dry-web-roda app with `config.warnings = true` in the spec config:

```
/Users/tim/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dry-transaction-0.8.0/lib/dry/transaction/sequence.rb:2: warning: loading in progress, circular require considered harmful - /Users/tim/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dry-transaction-0.8.0/lib/dry/transaction/dsl.rb
...
    from /Users/tim/Scratch/my_new_app/apps/main/component/main/transactions.rb:1:in  `<top (required)>'
    from /Users/tim/Scratch/my_new_app/apps/main/component/main/transactions.rb:1:in  `require'
    from /Users/tim/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dry-transaction-0.8.0/lib/dry-transaction.rb:1:in  `<top (required)>'
    from /Users/tim/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dry-transaction-0.8.0/lib/dry-transaction.rb:1:in  `require'
    from /Users/tim/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dry-transaction-0.8.0/lib/dry/transaction.rb:3:in  `<top (required)>'
    from /Users/tim/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dry-transaction-0.8.0/lib/dry/transaction.rb:3:in  `require'
    from /Users/tim/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dry-transaction-0.8.0/lib/dry/transaction/dsl.rb:4:in  `<top (required)>'
    from /Users/tim/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dry-transaction-0.8.0/lib/dry/transaction/dsl.rb:4:in  `require'
    from /Users/tim/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dry-transaction-0.8.0/lib/dry/transaction/sequence.rb:2:in  `<top (required)>'
    from /Users/tim/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dry-transaction-0.8.0/lib/dry/transaction/sequence.rb:2:in  `require'
```

### PR DESCRIPTION
**Pull request by mrbongiolo**
Fixes #38.

### CODE REVIEW

**Comment by solnic** [comment]
Looks like Sequence relies on `DSL` too, so that require is needed. In general we add requires for everything that a given file needs, even when it was already implicitly loaded by some other file

**Comment by mrbongiolo** [comment]
It relies on `DSL` to append or insert transactions, maybe this should be moved somewhere else. I'll take a look.

**Comment by timriley** [comment]
Since the DSL is only needed for those transaction manipulations, I wonder if we could just do this, and remove that top-of-file require:

``` ruby
      def accept_or_build_transaction(other_transaction = nil, **options, &block)
        unless other_transaction || block
          raise ArgumentError, "a transaction must be provided or defined in a block"
        end

        if other_transaction
          other_transaction
        else
          require "dry/transaction/dsl"
          DSL.new(**options, &block).call
        end
      end
```

**Comment by mrbongiolo** [comment]
@timriley I guess in that case this will be the best option. Unless we could append other transactions in a different way.

**Comment by timriley** [comment]
Thanks @mrbongiolo. Pulling this in now!

**Comment by timriley** [comment]
I've also made you a collaborator on this repo, @mrbongiolo. For future contributions, you're welcome to push to branches right here rather than on a fork.

**Pull request merged**
