### PR TITLE
[WIP][BUG] Dry::Transaction doesn't call parent initializer

### PR DESCRIPTION
**Pull request by radanskoric**
**The test on this PR will fail, that's expected.**  I first wanted to open an issue with just a script explaining repro steps but I found it easier to explain by adding a failing tests and also adding some comments directly in the code.

**The bug:** Currently, if a class includes `Dry::Transaction` it can't have any functionality relying on parent classes initializers being called because dry transaction doesn't call them.

**More details of the importance of the issue:** It is also relevant how I discovered this. In the project on which I'm working there are many operations which rely on dry-container, dry-auto_inject and when the operation is more complex we also use dry-transaction. Operations have a hierarchy with common parts extracted to base classes and some base classes also auto inject the components needed for all child operations. I tried to refactor one such child operation to use dry-transaction but it started breaking in a surprising way which lead me to find this bug.

This is the minimum repro script for the issue involving dry-container and auto_inject:
```
require 'dry-container'
require 'dry-auto_inject'
require 'dry-transaction'

class MyContainer
  extend Dry::Container::Mixin

  register "users_repository" do
    []
  end
end

Import = Dry::AutoInject(MyContainer)

class BaseUser
  include Import["users_repository"]
end

class CreateUser < BaseUser
  # If we comment this out the code works.
  include Dry::Transaction
  # Uncommenting the line below which is duplicated from base class is a workaround.
  # include Import["users_repository"]

  def foo(user_attrs)
    # This raises with: undefined method `push' for nil:NilClass (NoMethodError)
    users_repository.push(user_attrs)
  end
end

puts CreateUser.new.foo(name: "Jane")
```
As you can see above I found a workaround for my project but it is definitely not ideal.

I would gladly work on a fix but I don't know now what is a proper fix so any suggestion is very welcome

### CODE REVIEW

**Comment by radanskoric** [comment]
Any comments on this?

**Comment by timriley** [comment]
Hi @radanskoric thanks very much for your PR and detailed write up! Sorry I haven't gotten to it yet. I'll put aside some time for this early next week, thanks for your patience :)

**Comment by timriley** [comment]
Closing this one since we'll continue on from #97 (if at all). Thanks for getting this started!

**Comment by radanskoric** [comment]
Hi @timriley sorry, I forgot abut this MR. I was waiting on your response to wrap it up. :)

In the mean time my circumstances changed and I'm no longer using dry-transaction in any of my current projects so it's no longer relevant for my work. I don't like leaving unfinished work but I also don't see when I'd be able to pick that up again. If you don't think that #97 is important given the current state and plans for the gem, feel free to close it. :)

**Pull request closed without merging**
