### PR TITLE
Fix step notifications when passing step arguments

### LINKED ISSUE #60: Step notifications are disabled when passing args
Moving this across from #47:

> Passing step args seem to disable notifications for that step. This is
> a failing test to highlight the problem. It appears to be due to a new
> step instance being created without the subscribers attached.

### PR DESCRIPTION
**Pull request by jcmfernandes**
Fixes #60

### CODE REVIEW

**Comment by timriley** [comment]
Hi @jcmfernandes, thanks so much for making this fix! I've taken a look at the code and it looks good to me.

One thing I did notice, though: when running the specs, we're getting errors like this:

```
publishing_step_events_spec.rb:71: warning: already initialized constant Test::Container
publishing_step_events_spec.rb:18: warning: previous definition of Container was here
```

This is because we're redefining `Test::Container` in the nested `context "subscribing to step events when passing step arguments"` inside that spec file.

I reckon we'd be able to avoid these warnings if we defined the `:container` in ` let` block like this:

```ruby
    let(:container) {
      {
        process:  -> input { {name: input["name"]} },
        verify:   -> input, name { input[:name].to_s == name ? Dry::Monads.Right(input) : Dry::Monads.Left("wrong name") },
        persist:  -> input { Test::DB << input and true }
      }
    }
```

and then in our single top-level `before` block, just do this:

```ruby
before do
  Test::Container = container
  # ...
end
```

Would you mind making that change? Once we're warning-free here, this'll be good to merge! Thanks again! 👏

**Comment by jcmfernandes** [comment]
Hi @timriley! You're welcome :wink: it's me who has to thank you for your work and dedication to this project.

Your request is more than fair, it's the right way to do it. I forcefully pushed a new commit. Let me know what you think.

**Comment by timriley** [comment]
Looks great, thanks!

**Comment by jcmfernandes** [comment]
@timriley can I ask you for a new minor release? I have a feature ready in my current project that needs this to be working, and would like to avoid having a custom source in my Gemfile. Thanks!

**Comment by timriley** [comment]
@jcmfernandes 0.10.1 released for you 💁‍♂️

**Comment by jcmfernandes** [comment]
Thank you so much @timriley! :pray: :cake: :100:

**Pull request merged**
